### ISSUE TITLE
Missing Name ID 16/17 for regular/bold/italic/bolditalic

### ISSUE THREAD

**Issue by be5invis** [CatharsisFonts/Ysabeau#1]

**Comment by sergeevabc** [comment]
Not sure what this topic means, but the released fonts have different names than listed in ```readme.md```, i.e. EauTest instead of EauDeGaramond. It’s a bit confusing for sure.

**Comment by CatharsisFonts** [comment]
I haven't «released» any fonts yet. The font names show that these are still preliminary test versions.

The Roman should be fully functional by now, though. The Italic is far from finished, though. Latin letters and figures are done in a first version, but e.g. punctuation is not.

**Comment by sergeevabc** [comment]
Cannot stress enough what a hidden gem Eau de Garamond is, a rare sans for hours of gratifying reading.

**Comment by CatharsisFonts** [comment]
That's great to hear! 😬  Thanks for the feedback! 

I wish I could import fonts to my Kindle for testing, but it's not possible.

**Comment by sergeevabc** [comment]
Life without EauTest Italic is a pain, since a lot of decent authors (e.g. your countryman Carl Jung) use it to sharpen reader’s attention or emphasize [polysemy][1]. Dirty workaround is to use another italic like this:
```css
p em, p i {
    font-family: "Gentium Plus" !important;
}
```
What is the current state of affairs, @CatharsisFonts?
[1]: https://en.wikipedia.org/wiki/Polysemy

**Comment by CatharsisFonts** [comment]
I‘m currently applying for Google Fonts funding to complete Eau this year. I‘m going to be quite busy with my day job until summer, but establishing basic functionality for Eau Italic will be my first priority. 

Sent from my iPhone

**Comment by CatharsisFonts** [comment]
Aleksandr: While I haven't been sponsored by Google Fonts this year, I have fixed the basic punctuation and numbers in Eau Italic. Maybe it is now functional enough for your reading purposes? 😬

**Comment by sergeevabc** [comment]
@CatharsisFonts, it is encouraging to see you improving Eau Italic day by day. Six days ago only a few Cyrillic letters were rendered as expected, and today there are many more. Alas, » moved up.

![](https://images.vfl.ru/ii/1524912650/e3fa2f50/21540040.png)

**Comment by CatharsisFonts** [comment]
Thanks for the pointer! The Italic Cyrillic should be complete now (at least as far as the glyphs go). I do note that /ge-cy, /te-cy and /pe-cy are badly hinted at the baseline now, though. That wasn’t the case before. I’ll have to look into that.
