### ISSUE TITLE
Small caps italic

### ISSUE THREAD

**Issue by ezgranet** [CatharsisFonts/Ysabeau#12]
Would it be  possible please to make `+smcp`  work for italics? I've faked it in LaTeX by using smaller capital italic characters, but it would be lovely to have it properly

**Comment by CatharsisFonts** [comment]
It's not impossible, but very low on my priority list. I'd rather work on a headline cut or an IPA extension, for example.

**Comment by Chairzard** [comment]
> It's not impossible, but very low on my priority list. I'd rather work on a headline cut or an IPA extension, for example.

I just stumbled upon this and wanted to inquire to see if this is something you'd still consider. Adding italic small caps would benefit users of a couple of different e-reading apps/devices in particular. Off the top of my head: Kindles can display small cap glyphs, if the ebook being read supports enhanced typesetting (this includes italic small caps). KOReader will currently render text that uses italic small caps in lowercase if using Ysabeau, as it doesn't create fake small caps when they're missing from the font files; it would support proper italic small caps, if they were built-in.
