### ISSUE TITLE
Italics for ExtraBold / Black / Heavy weights?

### ISSUE THREAD

**Issue by cssobral2013** [CatharsisFonts/Ysabeau#13]

**Comment by CatharsisFonts** [comment]
Yes, that‘s the next big thing on my to-do list!

**Comment by sergeevabc** [comment]
What's the difference between Ysabeau and Ysabeau Office?

**Comment by CatharsisFonts** [comment]
Office promotes the OpenType features SS02 and TF to default, with three effects:

- Contextual use of long and superlong Q is suppressed.
- Slanted hyphens are replaced with horizontal hyphens.
- Oldstyle figures are replaced with tabular lining figures.

Cheers, Christian

**Comment by sergeevabc** [comment]
@CatharsisFonts, consider adding this data to the frontpage and/or readme, so that
other comrades don't have to search for it in the boondocks of the issue tracker.

**Comment by CatharsisFonts** [comment]
Done.
