### ISSUE TITLE
Odd line spacing on Mac

### ISSUE THREAD

**Issue by jandhau** [CatharsisFonts/Ysabeau#15]
I've observed that with the macOS programs Pages and Keynote the line height changes depending on the weight of the font.  
This may not be an issue with Ysabeau itself, because in Word, and even in Text Edit I don't get the behavior.  But in Pages and Keynote there are two line heights, that Ysabeau produces, one for thinner weights and another one for heavier weights (it only happens with Ysabeau, to my knowledge not with other fonts).  
All the lighter weights behave normally up to Regular.  
Italics now adds a few points to the line height and all the heavier weights keep the lines further apart. And then all the heavier weights keep the bigger line height.  

Check these images: 
![Screen Shot 2020-08-12 at 11 27 34 AM](https://user-images.githubusercontent.com/22217172/90053618-a94f2280-dcd2-11ea-9ca1-36216a1af002.png)
![Screen Shot 2020-08-12 at 11 27 44 AM](https://user-images.githubusercontent.com/22217172/90053616-a81df580-dcd2-11ea-88f6-a19cc24f6abc.png)
![Screen Shot 2020-08-12 at 11 33 55 AM](https://user-images.githubusercontent.com/22217172/90053741-cdaaff00-dcd2-11ea-98e0-e9e889d21345.png)

**Comment by CatharsisFonts** [comment]
Are you using an old version? I can't reproduce the issue in Keynote.
<img width="500" alt="Screenshot 2020-08-12 at 22 59 43" src="https://user-images.githubusercontent.com/13754106/90067553-90a13580-dcef-11ea-9d29-37263ae59a07.png">

**Comment by jandhau** [comment]
I'm using the one from the "latest release" page, Ysabeau_Install_v0.003
and I just redownloaded it, but still the same issue.

**Comment by jandhau** [comment]
I now downloaded the Master directly and this one works (The files in the "TrueType" folder)
So maybe the "latest" release just wasn't the latest?  ;)  

In any case, thanks for a wonderful font :)

**Comment by CatharsisFonts** [comment]
I haven't issued a release in a while, it seems. ;o) I'm really close to finishing the Black master of the uprights, so I'll make a new release then.
