### ISSUE TITLE
U+03CF GREEK CAPITAL KAI SYMBOL is too short

### ISSUE THREAD

**Issue by dscorbett** [CatharsisFonts/Ysabeau#16]
U+03CF GREEK CAPITAL KAI SYMBOL should be as tall as a capital letter. Here it is beside U+039A GREEK CAPITAL LETTER KAPPA.
![ΚϏ](https://user-images.githubusercontent.com/1124347/94979704-4ddf2b00-04f2-11eb-9477-beb3c670ba6c.png)

**Comment by CatharsisFonts** [comment]
I haven't seen many instances of the capital version so far, but the one on Wikipedia displays as smallcap-high on my machine (not sure which font; it might be a fallback). I'm happy to change it though if there's a clear preference for cap-high.

**Comment by dscorbett** [comment]
The examples in [L2/06-266](https://www.unicode.org/L2/L2006/06266-n3122-insular.pdf), figures 1–3 show it as caps-height and it is defined in Unicode as an uppercase letter. If you open your browser’s developer tools it should show you what font is being used on the Wikipedia article; I’m curious to know which font that is.

**Comment by CatharsisFonts** [comment]
I'm getting a rather unholy mix of fonts for that particular Wikipedia page. The capital Kai appears to be in Athelas for some reason. (I don't seem to have that installed on my machine, even though Wikipedia calls it an Apple system font.)
<img width="1087" alt="Screenshot 2020-10-04 at 00 28 45" src="https://user-images.githubusercontent.com/13754106/95002876-329b1b00-05d9-11eb-9587-819b8a1295f8.png">

**Comment by dscorbett** [comment]
I checked U+03CF in all the fonts I have that support it. All but two show it as caps-height. The exceptions are Athelas and Gill Sans. Gill Sans swaps the glyphs for U+03CF and U+03D7, which is a bug, not a design choice. System fonts often have bugs in obscure characters that go unfixed for years. I would therefore not trust Athelas.

**Comment by CatharsisFonts** [comment]
OK thanks. Better now?

**Comment by dscorbett** [comment]
It looks good now.
