### ISSUE TITLE
Ysabeau-SemiLight.ttf and YsabeauOffice-Ultrabold.ttf broken in build from 2021-02-15

### ISSUE THREAD

**Issue by RGB-es** [CatharsisFonts/Ysabeau#17]
As indicated in the title, both files fail to work: trying to open them in KDE's font viewer gives a "font cannot be read" error. Running 

`otfinfo -i Ysabeau-SemiLight.ttf `

I get 

`otfinfo: Ysabeau-SemiLight.ttf: OTF file corrupted (too small)`

**Comment by CatharsisFonts** [comment]
Yes, a pair of bugs in the current Glyphs 3 version were keeping me from successfully exporting all fonts. I used a workaround proposed by Georg Seifert to get new exports out with Glyphs 2. I hope it works now (and I hope the bug will be fixed soon enough to forego the workaround; it might be suppressing accented j in Dutch at the moment if I understand it correctly).

**Comment by RGB-es** [comment]
Thanks for the quick answer! SemiLight works now, but it seems that the new build is missing the Ysabeau-Book and Ysabeau-BookItalic files.

**Comment by CatharsisFonts** [comment]
I deprecated Book as an instance name since it’s so ill-defined (after reading a thread on TypeDrawers). I added SemiLight instead, which admittedly isn’t very conventional either... overall, the weight spectrum hasn’t changed.

**Comment by RGB-es** [comment]
Perfect! Thanks for your hard work!
