### ISSUE TITLE
Wrong glyphs in bold variant

### ISSUE THREAD

**Issue by VeskoRadic** [CatharsisFonts/Ysabeau#18]
In bold variants, some characters are not generated correctly: U+003A, U+003B, U+02BC. It seems to me that everything else is as it should be.

![image](https://user-images.githubusercontent.com/63882439/146998547-0e43153a-cffa-4da0-9808-2965a8c8d0c1.png)

EDIT: In fact, I have now noticed that it is the same with Ysabeau-Hairline.

**Comment by CatharsisFonts** [comment]
Dear Vesko,

thanks so much for bringing this up! The error was actually the glyph substitution code for the Office variant. My Python code that's supposed to keep it up to date apparently had been defunct for a while, and I hadn't noticed. I hope everything's fine now?

Cheers, Christian

**Comment by VeskoRadic** [comment]
It seems to me that everything is fine. If by any chance I notice something, I'll let you know :).

Thank you for such extraordinary fonts.
