### ISSUE TITLE
Bad interpolations for U+01D7 and U+01DB

### ISSUE THREAD

**Issue by dscorbett** [CatharsisFonts/Ysabeau#20]
The diaereses of U+01D7 LATIN CAPITAL LETTER U WITH DIAERESIS AND ACUTE and U+01DB LATIN CAPITAL LETTER U WITH DIAERESIS AND GRAVE are interpolated incorrectly. Here they are in Ysabeau Regular:
![ǗǛ](https://user-images.githubusercontent.com/1124347/153728595-e68ffe75-52b9-470b-8805-c531f3c96165.png)

**Comment by CatharsisFonts** [comment]
Thank you! Fixed.

Cheers, Christian
