### ISSUE TITLE
Interpolation issues - Roman - 2022-02-12

### ISSUE THREAD

**Issue by kenmcd** [CatharsisFonts/Ysabeau#21]
Found a few remaining interpolation issues in the Roman source.
YsabeauRoman.glyphs - posted approx. an hour ago.

IJ_acutecomb.liga and whiteCircle do appear broken in the static fonts.
The colonsign and peso.c2sc issues do not appear in the static fonts (because of the variation replacements), but you may still want to fix them.

![Roman-2022-02-12_14-40-59](https://user-images.githubusercontent.com/844920/153731243-f071e951-889b-4865-8cd8-f9a3cfa8720f.gif)

**Comment by AutismIsMySuperpower** [comment]
@kenmcd, I was checking if those interpolation issues (in the Roman) are still there and now they're gone. So I guess we can close this issue.

**Comment by CatharsisFonts** [comment]
Oh sorry, I forgot to reply! Yes, I fixed those, thanks. Cheers, Christian
