### ISSUE TITLE
Wrong shape of glyph U+040A

### ISSUE THREAD

**Issue by VeskoRadic** [CatharsisFonts/Ysabeau#25]
I noticed that the shape of the letter **Њ** (U+040A) was not correct.

The image, compared to several other fonts, shows the problematic part.

![image](https://user-images.githubusercontent.com/63882439/173339543-71111534-a126-42e5-98e3-311da6b195b9.png)

**Comment by CatharsisFonts** [comment]
Good point! Better now?

**Comment by VeskoRadic** [comment]
Much better :).

Thank you.
