### ISSUE TITLE
Suggestion for the numerals

### ISSUE THREAD

**Issue by dku9** [CatharsisFonts/Ysabeau#38]
This is one of prettiest & most legible sans-serif fonts I've ever seen.  I would like to use it as the default for my ebook reader & all my web browsing when in reader-mode.  However, do you think it's possible to create a variation of Ysabeau such that 1) the tops & bottoms of the numerals line up horizontally, and 2) none of the numerals appear to "dip" below other characters in a sentence?  My apologies for not having the technical knowledge to describe it in a more precise manner.  And sorry for suggesting to make it a little more boring!

**Comment by CatharsisFonts** [comment]
Hey, thanks! I also use Ysabeau on my Kindle and am very happy with it. :)

As for numerals, it sounds like the Ysabeau Office spin-off fonts might be exactly what you’re looking for?

Cheers, Christian

**Comment by dku9** [comment]
Oh wow...that's great!  I came from Google fonts and didn't know that there are so many variations.  My bad for not reading the project description carefully.  Thank you!
