### ISSUE TITLE
Change repo name

### ISSUE THREAD

**Issue by indolering** [CatharsisFonts/Ysabeau#7]
If you are going to rename the repo to Ysabeau, do it ASAP as the name-change will require manually updating local repos.  Certainly before any Beta or Alpha releases.

**Comment by CatharsisFonts** [comment]
I didn't know that was possible. How do I do that? Do I have to announce the change somehow?

**Comment by cmahte** [comment]
It's in repository settings.  It's best to  have no changes pending when
you change the name,  and be prepared to re initialize your local copy, in
case syncing goes crazy.

**Comment by CatharsisFonts** [comment]
Seems to have worked without problems. Thanks!
