### ISSUE TITLE
Mono Version?

### ISSUE THREAD

**Issue by indolering** [CatharsisFonts/Ysabeau#8]
I was thinking of creating a monospaced version of this font, I think it would make a great competitor to Operator Mono!

Any thoughts?

**Comment by CatharsisFonts** [comment]
I'm personally not interested in monospaced fonts, so if you feel like doing it, be my guest. 😬

Might that be worth creating a new branch?

**Comment by indolering** [comment]
> I'm personally not interested in monospaced fonts

You should check out [Operator Pro](https://www.typography.com/blog/introducing-operator), it can be a fun design constraint!

> so if you feel like doing it, be my guest. 😬

If I do this, I would like to keep it in sync with the core project.  That means a lot of scripted transforms....

> Might that be worth creating a new branch?

Agreed.

**Comment by CatharsisFonts** [comment]
I love Operator, though mostly for the natural-width version. The unsolvable /m/ problem just ruins monospaced fonts for me. 

The Hairline and Medium masters of Ysabeau should be pretty stable now, so I’d hope you could start on those weights of the mono with little need for frequent adjustments.

**Comment by indolering** [comment]
> I love Operator, though mostly for the natural-width version.

It is just delicious!  I strongly dislike most programming-oriented fonts.  They generally feel like amateurish attempts by programmers.  I was contemplating manually outline raster type samples of Operator Mono until I found this.

> The unsolvable /m/ problem just ruins monospaced fonts for me.

Elucidate, please?  I don't get to do much design work anymore 😀.

> The Hairline and Medium masters of Ysabeau should be pretty stable now, so I’d hope you could start on those weights of the mono with little need for frequent adjustments.

I'm pretty busy, so I'll wait.

I'm not sure how to approach lowercase "l" and uppercase "I", mind working those glyphs for me?
