### ISSUE TITLE
Remove .DS_Store files, add .gitignore.

### ISSUE THREAD

**Issue by jenstroeger** [CatharsisFonts/Ysabeau#9]
I’ve noticed that you have a bunch of local, Mac specific [`.DS_Store`](https://en.wikipedia.org/wiki/.DS_Store) files checked into this repo. They should probably be removed:
```terminal
ysabeau > find . -name '.DS_Store' -exec git rm {} \;
rm '1. TrueType Font Files/.DS_Store'
rm '2. OpenType Font Files (not up to date)/.DS_Store'
rm '3. Glyphs Source Files/.DS_Store'
rm '4. Legacy Font Files/.DS_Store'
```
You can then add a new file [`.gitignore`](https://git-scm.com/docs/gitignore) to the root of this repo which contains a single line
```
.DS_Store
```
telling git to ignore these files. I’ve got a branch here with the changes, but can’t push; they’re easy enough, though, for you to add them yourself… 😉

**Comment by CatharsisFonts** [comment]
Better? 😬
